routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes([
    // 'register'=> false,
]);

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/welcome', 'MainPageController@index')->name('welcome');
Route::get('/', 'MainPageController@index')->name('welcome');
Route::name('front.')->group(function () {
    Route::get('about-us', 'AboutUsController@index')->name('about-us');
    Route::get('about-apart', 'AboutApartController@index')->name('about-apart');
    Route::get('galery', 'GaleryController@index')->name('galery');
    Route::get('contact', 'ContactController@index')->name('contact');
});

Route::name('errors.')->group(function () {
    Route::get('/404', 'HomeController@index')->name('404');
    Route::get('/500', 'HomeController@index')->name('500');
});


Route::get('/revenue-report', 'ReportRevenueController@index')->name('report.revenue');

Auth::routes();

/* --- CRUD Controllers - START --- */
Route::resource('users', UserCRUDController::class);  //Kullanıcılar
Route::resource('tenants', TenantCRUDController::class);  //Kiracı
Route::resource('revenues', RevenueCRUDController::class);  //Gelirler
Route::resource('expenses', ExpenseCRUDController::class);  //Giderler
Route::resource('expense_lists', ExpenseListCRUDController::class);  //Gider Türleri
Route::resource('room_det', RoomDetCRUDController::class);  //Odalar
Route::resource('aboutus', AboutusCRUDContoller::class);  //Hakkımızda
Route::resource('aboutapart', AboutapartCRUDController::class);  //Apart Hakkında
Route::resource('contacts', ContactCRUDController::class);  //İletişim
Route::resource('rooms', RoomCRUDController::class);  //Odalar
Route::resource('floors', FloorCRUDController::class);  //Katlar


Route::resource('whyapart', WhyapartCRUDController::class);  //Neden Üsküdar Apart
Route::resource('locationitem', LocationItemCRUDController::class);  //Konum Maddeleri
Route::resource('apartproperty', ApartPropertyCRUDController::class);  //Apart Özellikleri
Route::resource('photogalery', PhotoGaleryCRUDController::class);  //Fotoğraf Galerisi



/* --- CRUD Controllers - END --- */

Route::get('/user', 'UserController@index')->name('admin.users.list');

Route::namespace('Auth')->group(function () {
    Route::get('logout', 'LoginController@logout');
});

resources/views/front/about-apartment.blade.php
@extends('layouts.outside')

@section('content')

<div id="Content">
    <div class="content_wrapper clearfix">
        <div class="sections_group">
            <div class="entry-content">
                <div class="section" style="padding-top:100px; padding-bottom:60px; background-image:url(images/home_developer_photo_subheader.jpg); background-repeat:no-repeat; background-position:center top; background-attachment:fixed;">
                    <div class="section_wrapper clearfix">
                        <div class="items_group clearfix">
                            <!-- One full width row-->
                            <div class="column one column_column ">
                                <div class="column_attr align_center">
                                    @foreach($aboutaparts as $aboutapart)
                                    <h2 class="subheader"> {{$aboutapart->title}}</h2>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="section column-margin-20px" style="padding-top:40px; padding-bottom:30px; ">
                    <div class="section_wrapper clearfix">
                        <div class="items_group clearfix">
                            <!-- One Sixth (1/6) Column -->
                            <div class="column one-sixth column_placeholder">
                                <div class="placeholder">
                                    &nbsp;
                                </div>
                            </div>
                            <!-- Two Third (2/3) Column -->
                            <div class="column two-third column_column ">
                                <div class="column_attr align_center">
                                    @foreach($aboutaparts as $aboutapart)
                                    <p style="font-size: 17px; line-height: 30px; font-style: italic; color: #F1B000;">
                                        {{$aboutapart->paragraph}} 
                                    </p>
                                    @endforeach
                                </div>
                            </div>
                            @foreach($aboutaparts as $aboutapart)
                            <!-- One Second (1/2) Column -->
                            <div class="column one-second column_column ">
                                <div class="column_attr ">
                                    <p class="big">
                                    {{$aboutapart->paragraph1}} 
                                    </p>
                                </div>
                            </div>
                            <!-- One Second (1/2) Column -->
                            <div class="column one-second column_column ">
                                <div class="column_attr ">
                                    <p>
                                    {{$aboutapart->paragraph2}} 
                                    </p>
                                </div>
                            </div>
                            @endforeach
                            

                            @include('front.rooms')
                        </div>
                    </div>
                </div>
                <div class="section the_content no_content">
                    <div class="section_wrapper">
                        <div class="the_content_wrapper"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

@endsection

resources/views/front/about-us.blade.php
@extends('layouts.outside')

@section('content')
<div id="Content">
            <div class="content_wrapper clearfix">
                <div class="sections_group">
                    <div class="entry-content">
                        <div class="section" style="padding-top:100px; padding-bottom:60px; background-image:url(images/home_developer_photo_subheader.jpg); background-repeat:no-repeat; background-position:center top; background-attachment:fixed;">
                            <div class="section_wrapper clearfix">
                                <div class="items_group clearfix">
                                    <!-- One full width row-->
                                    <div class="column one column_column ">
                                        <div class="column_attr align_center">
                                            <h2 class="subheader">Hakkımızda</h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="section column-margin-20px" style="padding-top:40px; padding-bottom:10px; ">
                            <div class="section_wrapper clearfix">
                                <div class="items_group clearfix">
                                    <!-- One full width row-->
                                    <div class="column one column_column ">
                                        <div class="column_attr align_center">
                                            <div class="image_frame no_link scale-with-grid aligncenter no_border">
                                                <div class="image_wrapper"><img class="scale-with-grid" src="{{ asset('images/home_developer_thumb_slider_icon_1.png') }}" alt="" />
                                                </div>
                                            </div>
                                            @foreach($aboutuses as $aboutus)
                                            <h2 style="text-align: center;">{{$aboutus->title}}</h2>
                                            @endforeach
                                        </div>
                                    </div>
                                    <!-- One Second (1/2) Column -->
                                    <div class="column one-second column_image ">
                                        <div class="image_frame no_link scale-with-grid aligncenter no_border">
                                            <div class="image_wrapper"><img class="scale-with-grid" src="{{ asset('images/home_developer_thumb_slider_1.png') }}" alt="" />
                                            </div>
                                        </div>
                                    </div>
                                    <!-- One Second (1/2) Column -->
                                    <div class="column one-second column_column ">
                                        <div class="column_attr ">
                                            <hr class="no_line hrmargin_b_20" />
                                            @foreach($aboutuses as $aboutus)
                                            <!-- One Second (1/2) Column -->
                                            <div class="column one-second">
                                            
                                                <p class="big">
                                                {{$aboutus->paragraph1}}
                                                </p>
 
                                            </div>
                                            <!-- One Second (1/2) Column -->
                                            <div class="column one-second">
                                                <p class="big">
                                                {{$aboutus->paragraph2}}
                                                </p>
                                              
                                            </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="section the_content no_content">
                            <div class="section_wrapper">
                                <div class="the_content_wrapper"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

resources/views/front/contact.blade.php
@extends('layouts.outside')

@section('content')
<div id="Content">
	<div class="content_wrapper clearfix">
		<div class="sections_group">
			<div class="entry-content">
				<div class="section" style="padding-top:100px; padding-bottom:60px; background-image:url(images/home_developer_photo_subheader.jpg); background-repeat:no-repeat; background-position:center top; background-attachment:fixed;">
					<div class="section_wrapper clearfix">
						<div class="items_group clearfix">
							<!-- One full width row-->
							<div class="column one column_column ">
								<div class="column_attr align_center">
								@foreach($contacts as $contact)
									<h2 class="subheader">{{$contact->title}} </h2>
								@endforeach
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="section full-width sections_style_0 ">
					<div class="section_wrapper clearfix">
						<div class="items_group clearfix">
							<!-- One full width row-->
							<div class="column one column_map ">

								<!-- Google map area -->
								<div class="google-map-wrapper no_border">
								<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d376.2543259229571!2d29.017298!3d41.0244988!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14cab78be5dbaa03%3A0xc21b162757bb35b3!2sBosch!5e0!3m2!1str!2str!4v1563795477142!5m2!1str!2str" width="100%" height="410" frameborder="0" style="border:0"></iframe>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="section" style="padding-top:40px; padding-bottom:0px; background-color:#ffba00">
					<div class="section_wrapper clearfix">
						<div class="items_group clearfix">
							<!-- One full width row-->
							<div class="column one column_column ">
								<div class="column_attr align_center">
									@foreach($contacts as $contact)
										<h2 style="margin: 0; color: #fff;">Bizi Arayın {{$contact->phone}} </h2>
									@endforeach
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="section" style="padding-top:50px; padding-bottom:10px; background-image:url(images/home_developer_section_gallery.jpg); background-repeat:no-repeat; background-position:center; ">
					<div class="section_wrapper clearfix">
						<div class="items_group clearfix">
							<!-- One Fourth (1/4) Column -->
							<div class="column one-fourth column_column ">
								<div class="column_attr ">
									<h3>Üsküdar Apart</h4>
										@foreach($contacts as $contact)
										<p class="big">
										<strong>Adres:</strong> {{$contact->adress}} <br>
										<strong>E-Mail:</strong> {{$contact->email}}
										</p>
										@endforeach
										<table>
											<tr>
												<td>Pzt-Cuma</td><td><b>10:00</b></td><td><b>20:00</b></td>
											</tr>
											<tr>
												<td>Cmt</td><td><b>10:00</b></td><td><b>20:00</b></td>
											</tr>
											<tr>
												<td>Paz</td><td><b>10:00</b></td><td><b>20:00</b></td>
											</tr>
										</table>
									</div>
								</div>
								<!-- One Second (1/2) Column -->
								<div class="column one-second column_column ">
									<div class="column_attr " >
										<h3>Formu Doldur Hemen Arayalım</h4>
										<div id="contactWrapper" >
									<form id="contactform">
										<div class="column one-second">
											<input placeholder="Ad" type="text" name="name" id="name" size="40" aria-required="true" aria-invalid="false" />
										</div>
										<div class="column one-second">
											<input placeholder="E-Mail" type="email" name="email" id="email" size="40" aria-required="true" aria-invalid="false" />
										</div>
										<div class="column one-second">
											<input placeholder="Telefon" type="tel" name="tel" id="tel" size="40" aria-required="true" aria-invalid="false" />
										</div>
										<!-- <div class="column one">
											<input placeholder="Subject" type="text" name="subject" id="subject" size="40" aria-invalid="false" />
										</div> -->
										<div class="column one">
											<textarea placeholder="Mesaj" name="body" id="body" style="width:100%;" rows="10" aria-invalid="false"></textarea>
										</div>
										<div class="column one">
											<input type="button" value="Gönder" id="submit" onClick="return check_values();">
										</div>
									</form>
								</div>
									</div>
								</div>
								<!-- One Fourth (1/4) Column -->
								<div class="column one-fourth column_column ">
									<div class="column_attr " >
									@foreach($contacts as $contact)
										<h3>{{$contact->title}}</h4>
									
										<p class="big">
										{{$contact->paragraph}}
										</p>
										
									@endforeach
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="section the_content no_content">
						<div class="section_wrapper">
							<div class="the_content_wrapper"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/front/footer.blade.php
<footer id="Footer" class="clearfix">
    <!-- Footer - First area -->
    <div class="footer_action">
        <div class="container">
            <!-- One full width row-->
            <div class="column one column_column">
                <a href="#" style="text-decoration: none; color: #CCCCCC;" target="_blank"><span style="font-size: 18px">Detaylı Bilgi Almak için <span class="themecolor">Üsküdar |</span><span style="color: #fff;"> Apart'ı</span> hemen arayın <span style="color: #fff;"><a href="{{ route('front.contact') }}">TIKLA!</a></span></span></a>
            </div>
        </div>
    </div>
    <div class="widgets_wrapper">
        <div class="container">
            <div class="one-fourth column">
                <!-- Text Area -->
                <aside id="text-7" class="widget widget_text">
                    <div class="textwidget"><img src="{{ asset('images/logo_footer.png') }}" alt="" width="130" height="30" />
                        <p>
                            <span class="big">Kendinizi mutlu, huzurlu ve güvende hissedebileceğiniz</span>
                            <span class="big">eviniz gibi benimseyeceğiniz, harika arkadaşlık</span>
                            <span class="big">bağlarının olduğu eğlenceli,neşeli bir apart.</span>
                        </p>
                        <p>
                            
                        </p> 
                        <a href="https://facebook.com/" target="blank" class="icon_bar icon_bar_facebook icon_bar_small"><span class="t">
                            <i class="fab fa-facebook-f"></i></span><span class="b">
                            <i class="fab fa-facebook-f"></i></span>
                        </a>

                        <a href="https://twitter.com/" target="blank" class="icon_bar icon_bar_twitter icon_bar_small"><span class="t">
                            <i class="fab fa-twitter"></i></span><span class="b">
                            <i class="fab fa-twitter"></i></span>
                        </a>

                        <a href="https://www.youtube.com/watch?v=3bWaJsOzRK4?autoplay=0" target="blank" class="icon_bar icon_bar_youtube icon_bar_small"><span class="t">
                            <i class="fab fa-youtube"></i></span><span class="b">
                            <i class="fab fa-youtube"></i></span>
                        </a>
                    </div>
                </aside>
            </div>
            <div class="one-fourth column">
                <!-- Recent Comments Area -->
                <aside class="widget widget_mfn_recent_comments">
                    <h4>Sayfalar</h4>
                    <div class="Recent_comments">
                        <ul class="menu">
                            <li>
                                <span class="date_label"><a href="{{ route('front.about-us')}}">Hakkımızda</a></span>
                            </li>
                            <li>
                                <span class="date_label"><a href="{{ route('front.about-apart')}}">Apart Hakkında</a></span>
                            </li>
                            <li>
                                <span class="date_label"><a href="{{ route('front.galery')}}">Galeri</a></span>
                            </li>
                            <li>
                                <span class="date_label"><a href="{{ route('front.contact')}}">İletişim</a></span>
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
            <div class="one-fourth column">
                <!-- Recent posts -->
                <aside class="widget widget_mfn_recent_posts">
                    <h4>Çamaşır Yıkama</h4>
                    <div class="Recent_posts">
                        <ul>
                            <li class="post ">
                                <a href="blog-single-content-builder.html">
                                    <div class="photo"><img width="80" height="80" src="{{ asset('images/beauty_portfolio_2-80x80.jpg') }}" class="scale-with-grid wp-post-image" alt="beauty_portfolio_2" /><span class="c"><i class="fas fa-check"></i></span>
                                    </div>
                                    <div class="desc">
                                        <h6>Haftaiçi</h6><span class="date"><i class="far fa-clock"></i> 07:00 - 22:00</span>
                                    </div>
                                </a>
                            </li>
                            <li class="post format-image">
                                <a href="blog-single-vertical-photo.html">
                                    <div class="photo"><img width="80" height="80" src="{{ asset('images/blog_vertical-80x80.jpg') }}" class="scale-with-grid wp-post-image" alt="blog_vertical" /><span class="c"><i class="fas fa-check"></i></span>
                                    </div>
                                    <div class="desc">
                                        <h6>Haftasonu</h6><span class="date"><i class="far fa-clock"></i>07:00 - 23:59</span>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
            <div class="one-fourth column">
                <!-- Text Area -->
                <aside id="text-8" class="widget widget_text">
                    <h4>ÖNEMLİ BİLGİLENDİRME</h4>
                    <div class="textwidget">
                        <ul class="list_mixed">
                            <li class="list_check">
                                Apartımıza Öğrenci Alınmamaktadır.
                            </li>
                            <li class="list_star">
                                Depozito, Komiyon, Kapora Yok.
                            </li>
                            <li class="list_idea">
                                Her Yere Ulaşım Kolaylığı.
                            </li>
                            <li class="list_check">
                               En Az Bir Aylık Konaklama İmkanı.
                            </li>
                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <!-- Footer copyright-->
    <div class="footer_copy">
        <div class="container">
            <div class="column one">
                <a id="back_to_top" href="#" class="button button_left button_js"><i class="fas fa-chevron-up fa-2x"></i></a>
                <div class="copyright">
                    &copy; 2019 ABY - Developer <a href="https://www.linkedin.com/in/abyener/" target="_blank">Abdulbasid Yener</a>
                </div>
                <!--Social info area-->
                <ul class="social">
                    <li class="facebook">
                        <a href="https://www.facebook.com/" title="Facebook"><i class="fab fa-facebook-f"></i></a>
                    </li>
                   
                    <li class="twitter">
                        <a href="https://twitter.com/" title="Twitter"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="youtube">
                        <a href="https://www.youtube.com/watch?v=3bWaJsOzRK4?autoplay=0" title="YouTube"><i class="fab fa-youtube"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/front/header.blade.php
<div id="Header_creative">
    <a href="#" class="creative-menu-toggle"><i class="fas fa-bars"></i></a>
    <!--Social info area-->
    <ul class="social creative-social">
        
        <li class="facebook">
            <a target="_blank" href="https://facebook.com/" title="Facebook"><i class="fab fa-facebook-f"></i></a>
        </li>
       
        <li class="twitter">
            <a target="_blank" href="https://twitter.com/" title="Twitter"><i class="fab fa-twitter"></i></a>
        </li>
       
        <li class="youtube">
            <a target="_blank" href="https://www.youtube.com/watch?v=3bWaJsOzRK4?autoplay=0" title="YouTube"><i class="fab fa-youtube"></i></a>
        </li>
      
    </ul>
    <div class="creative-wrapper">
        <!-- Header -  Logo and Menu area -->
        <div id="Top_bar">
            <div class="one">
                <div class="top_bar_left">
                    <!-- Logo-->
                    <div class="logo">
                        <a id="logo" href="{{ route('welcome') }}" title="Üsküdar Apart"><img class="scale-with-grid" src="{{ asset('images/developer.png') }}" alt="BeDeveloper - BeTheme" />
                        </a>
                    </div>
                    <!-- Main menu-->
                    <div class="menu_wrapper">
                        <nav id="menu">
                            <ul id="menu-main-menu" class="menu">
                                <li class="current_page_item">
                                    <a href="{{ route('welcome') }}"><span>Anasayfa</span></a>
                                </li>
                                <li>
                                    <a href="{{ route('front.about-us') }}"><span>Hakkımızda</span></a>
                                </li>

                                <li>
                                    <a href="{{ route('front.about-apart') }}"><span>Apart Hakkında</span></a>
                                </li>
                                <li>
                                    <a href="{{ route('front.galery') }}"><span>Galeri</span></a>
                                </li>
                                <li>
                                    <a href="{{ route('front.contact') }}"><span>İletişim</span></a>
                                </li>
                            </ul>
                        </nav><a class="responsive-menu-toggle" href="#"><i class="fas fa-bars"></i></a>
                    </div>
                    <!-- Header Searchform area-->
                    <div class="search_wrapper">
                        <form method="get" id="searchform" action="#">
                            <i class="icon_search icon-search"></i><a href="#" class="icon_close"><i class="icon-cancel"></i></a>
                            <input type="text" class="field" name="s" id="s" placeholder="Enter your search" />
                            <input type="submit" class="submit flv_disp_none" value="" />
                        </form>
                    </div>
                </div>
                <!-- Banner area - only for certain pages-->
                <div class="banner_wrapper"></div>
            </div>
        </div>
        <!-- Header Top -  Info Area -->
        <div id="Action_bar">
            <!--Social info area-->
            <ul class="social">
                <li class="facebook">
                    <a target="_blank" href="https://www.facebook.com/" title="Facebook"><i class="fab fa-facebook-f"></i></a>
                </li>
                
                <li class="twitter">
                    <a target="_blank" href="https://www.twitter.com/" title="Twitter"><i class="fab fa-twitter"></i></a>
                </li>
               
                <li class="youtube">
                    <a target="_blank" href="https://www.youtube.com/watch?v=3bWaJsOzRK4?autoplay=0" title="YouTube"><i class="fab fa-youtube"></i></a>
                </li>
        
            </ul>
        </div>
    </div>
</div>

resources/views/front/rooms.blade.php
<div class="column one column_column ">
    <div class="column_attr ">
        <hr class="no_line hrmargin_b_20" />
        <h4 style="text-align: center;">Odalar Hakkında Bilgi <span class="highlight" >Ü</span></h4>
        <hr class="no_line hrmargin_b_30" />
        <table>
            <thead>
                <tr>
                    <th>Sıra</th>
                    <th>Oda Sayısı</th>
                    <th>Yatak Sayısı</th>
                    <th>Dolap Sayısı</th>
                    <th>Buzdolabı Sayısı</th>
                    <th>Klima</th>
                    <th>Çamaşır Makinası</th>
                    <th>Televizyon</th>
                    <th>Mutfak</th>
                    <th>Tuvalet/Banyo</th>
                    <th>Ücret</th>
                    <th>Görüntü</th>
                </tr>
            </thead>
            <tbody>
            @foreach($roomdets as $roomdet) 
                <tr>
                    <td>{{$roomdet->id}}</td>
                    <td>{{$roomdet->room}}</td>
                    <td>{{$roomdet->beds}}</td>
                    <td>{{$roomdet->cabinets}}</td>
                    <td>{{$roomdet->refrigerator}}</td>
                    <td>{{$roomdet->klima}}</td>
                    <td>{{$roomdet->washing_machine}}</td>
                    <td>{{$roomdet->television}}</td>
                    <td>{{$roomdet->kitchen}}</td>
                    <td>{{$roomdet->bathroom}}</td>
                    <td>{{$roomdet->price}}</td>
                    <td>
                        <a href="{{ route('front.galery')}}" target="blank"><i class="far fa-images fa-3x"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>